# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Q Schedule App Build

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js version
        uses: actions/setup-node@v1
        with:
          node-version: "18.x"

      - name: npm install, build, and test
        run: |
          npm install
          npm run build --if-present
          npm run test --if-present

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v2
        with:
          name: node-app
          path: ./dist

  deploy-development:
    name: development
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: "development"
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: node-app

      - name: "Deploy to Azure Web Dev"
        uses: azure/webapps-deploy@v2
        id: deploy-to-webapp
        with:
          app-name: "q-schedule-dev"
          slot-name: "production"
          publish-profile: ${{ secrets.AzureAppService_PublishProfile_1234 }}
          package: .

      - name: "Login via Azure CLI"
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Set Configs for dev
        uses: Azure/appservice-settings@v1
        with:
          app-name: "q-schedule-dev"
          app-settings-json: |
            [
              {
                  "name": "FIREBASE_API_KEY",
                  "value": "${{ vars.FIREBASE_API_KEY }}",
                  "slotSetting": false
              },
              {
                  "name": "FIREBASE_APP_ID",
                  "value": "${{ vars.FIREBASE_APP_ID }}",
                  "slotSetting": false
              },
              {
                  "name": "FIREBASE_AUTH_DOMAIN",
                  "value": "${{ vars.FIREBASE_AUTH_DOMAIN }}",
                  "slotSetting": false
              },
              {
                  "name": "FIREBASE_DATABASE_URL",
                  "value": "${{ vars.FIREBASE_DATABASE_URL }}",
                  "slotSetting": false
              },
              {
                  "name": "FIREBASE_MESSENGING_SENDER_ID",
                  "value": "${{ vars.FIREBASE_MESSENGING_SENDER_ID }}",
                  "slotSetting": false
              },
              {
                  "name": "FIREBASE_PROJECT_ID",
                  "value": "${{ vars.FIREBASE_PROJECT_ID }}",
                  "slotSetting": false
              },
              {
                  "name": "FIREBASE_STORAGE_BUCKET",
                  "value": "${{ vars.FIREBASE_STORAGE_BUCKET }}",
                  "slotSetting": false
              }
            ]

  deploy-production:
    name: production
    runs-on: ubuntu-latest
    needs: [build, deploy-development]
    environment:
      name: "production"
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: node-app

      - name: "Deploy to Azure Web Prod"
        uses: azure/webapps-deploy@v2
        id: deploy-to-webapp
        with:
          app-name: "q-schedule-prod"
          slot-name: "production"
          publish-profile: ${{ secrets.AzureAppService_PublishProfile_Prod }}
          package: .

      - name: "Login via Azure CLI"
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Set Configs for prod
        uses: Azure/appservice-settings@v1
        with:
          app-name: "q-schedule-prod"
          app-settings-json: |
            [
              {
                  "name": "FIREBASE_API_KEY",
                  "value": "${{ vars.FIREBASE_API_KEY }}",
                  "slotSetting": false
              },
              {
                  "name": "FIREBASE_APP_ID",
                  "value": "${{ vars.FIREBASE_APP_ID }}",
                  "slotSetting": false
              },
              {
                  "name": "FIREBASE_AUTH_DOMAIN",
                  "value": "${{ vars.FIREBASE_AUTH_DOMAIN }}",
                  "slotSetting": false
              },
              {
                  "name": "FIREBASE_DATABASE_URL",
                  "value": "${{ vars.FIREBASE_DATABASE_URL }}",
                  "slotSetting": false
              },
              {
                  "name": "FIREBASE_MESSENGING_SENDER_ID",
                  "value": "${{ vars.FIREBASE_MESSENGING_SENDER_ID }}",
                  "slotSetting": false
              },
              {
                  "name": "FIREBASE_PROJECT_ID",
                  "value": "${{ vars.FIREBASE_PROJECT_ID }}",
                  "slotSetting": false
              },
              {
                  "name": "FIREBASE_STORAGE_BUCKET",
                  "value": "${{ vars.FIREBASE_STORAGE_BUCKET }}",
                  "slotSetting": false
              }
            ]
